### ISSUE TITLE
iOS Issues

### ISSUE THREAD

**Issue by JouzaLoL** [JouzaLoL/better-zastupovani#45]
https://sentry.io/josef-vacek/zastupovani/issues/491170791/

```
TypeError: null is not an object (evaluating 'p.suplovani')
  at render (/main.js:1:285206)
  at onFilterChange (/main.js:1:288450)
  at dispatch (/main.js:1:191148)
  at handle (/main.js:1:189150)
  at r (/main.js:1:234453)
```

**Comment by JouzaLoL** [comment]
https://sentry.io/josef-vacek/zastupovani/issues/496646857/
